config/routes.rb
Rails.application.routes.draw do
  resources :books do
    get :search, on: :collection
    get :form_only_for_stimulus, on: :collection
    get :list_all, on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :publisher, optional: true
  belongs_to :author, optional: true

  accepts_nested_attributes_for :author
  accepts_nested_attributes_for :publisher

  broadcasts_to ->(book) {'books'}, target: :books, inserts_by: :prepend
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  def form_only_for_stimulus
    @book = Book.new
    @author = @book.build_author
  end

  def list_all
    @books = Book.order(created_at: :desc)
    @date_wise_count = Book.order(:created_at).group("DATE(created_at)").count
    respond_to do |format|
      format.html 
      format.json {
        render :json => {dates: @date_wise_count.keys, counts: @date_wise_count.values}
      }
    end
  end

  # GET /books or /books.json
  def index
    @books = Book.order(created_at: :desc)
    # @book = Book.new
  end

  def search
    if params[:query]
      @books = Book.where("title LIKE ?", "%#{params[:query]}%")
    else
      @books = Book.order(created_at: :desc)
    end
    respond_to do |format|
      format.html
      format.json { render json: { books: @books } }
    end
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    @author = @book.build_author
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to books_url, notice: "Book was successfully created." }
        format.json { render :index, status: :created, location: @book }
      else
        # format.html { render :new, status: :unprocessable_entity }
        format.html { redirect_to books_url, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :description, :isbn, :total_pages, :published_date, author_attributes: [:id, :name, :contact_number])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<%= turbo_frame_tag book do %>
  <div class="card mb-3">
    <div class="card-body"> 
      <h5 class="card-title"><%= book.title %></h5>
      <p class="card-text"><%= book.isbn %> | <%= book.total_pages %></p>
      <p class="card-text"><%= book.published_date %></p>
      <p class="card-text"><%= book.try(:author).try(:name) %></p>
    </div>
    <div class="card-footer">
      <%= link_to 'Show', book, 'data-turbo-frame': "_top" %> | <%= link_to 'Edit', edit_book_path(book), 'data-turbo-frame': "_top" %> | 
      <%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
<% end %>

app/views/books/_book_list.html.erb
<% books.each do |book| %>
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title"><%= book.title %></h5>
      <p class="card-text"><%= book.isbn %> | <%= book.total_pages %></p>
      <p class="card-text"><%= book.published_date %></p>
      <p class="card-text"><%= book.try(:author).try(:name) %></p>
    </div>
    <div class="card-footer">
      <%= link_to 'Show', book %> | <%= link_to 'Edit', edit_book_path(book) %> |
      <%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
<% end %>

app/views/books/_form.html.erb
<%= form_with(model: book, id: "books-form") do |form| %>
  <div class="row">
    <% if book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

        <ul>
          <% book.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-6">
      <div class="form-group row">
        <label for="book_title" class="col-sm-3 col-form-label">Title</label>
        <div class="col-sm-9">
          <%= form.text_field :title, class: "form-control required", placeholder: "Title" %>
        </div>
      </div>
    </div>
    <div class="col-6">
      <div class="form-group row">
        <label for="book_isbn" class="col-sm-3 col-form-label">ISBN</label>
        <div class="col-sm-9">
          <%= form.text_field :isbn, class: "form-control required", placeholder: "ISBN" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-6">
      <div class="form-group row">
        <label for="book_total_pages" class="col-sm-3 col-form-label">Total Pages</label>
        <div class="col-sm-9">
          <%= form.text_field :total_pages, class: "form-control required", placeholder: "Total Pages" %>
        </div>
      </div>
    </div>
    <div class="col-6">
      <div class="form-group row">
        <label for="book_published_date" class="col-sm-3 col-form-label">Published Date</label>
        <div class="col-sm-9">
          <%= form.date_field :published_date, class: "form-control required", placeholder: "Published Date" %>
        </div>
      </div>
    </div>
  </div>

  <%= form.fields_for :author_attributes do |a|%>
    <div class="row">
      <div class="col-6">
        <div class="form-group row">
          <label for="book_name" class="col-sm-3 col-form-label">Author Name</label>
          <div class="col-sm-9">
            <%= a.text_field :name, class: "form-control required", placeholder: "Author Name" %>
          </div>
        </div>
      </div>
      <div class="col-6">
        <div class="form-group row">
          <label for="book_contact_number" class="col-sm-3 col-form-label">Author Contact Number</label>
          <div class="col-sm-9">
            <%= a.text_field :contact_number, class: "form-control required", placeholder: "Author Contact Number" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-3" data-controller="books">
      <div class="form-group">
        <%= form.submit class: "btn btn-primary", data: {action: "click->books#validate_form"} %>
      </div>
    </div>
  </div>

<% end %>

app/views/books/edit.html.erb
<div class="col-12">
  <h1>Editing Book</h1>

  <%= render 'form', book: @book %>

  <%= link_to 'Show', @book %> |
  <%= link_to 'Back', books_path %>
</div>

app/views/books/form_only_for_stimulus.html.erb
<div class="col-12">
<%= form_with(model: @book, class: "mt-4", id: "books-form") do |form| %>
  <div class="row">
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

        <ul>
          <% @book.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-10">
      <div class="form-group row">
        <label for="book_title" class="col-sm-3 col-form-label">Title</label>
        <div class="col-sm-9">
          <%= form.text_field :title, class: "form-control required", placeholder: "Title" %>
        </div>
      </div>
    </div>
    <div class="col-10">
      <div class="form-group row">
        <label for="book_isbn" class="col-sm-3 col-form-label">ISBN</label>
        <div class="col-sm-9">
          <%= form.text_field :isbn, class: "form-control required", placeholder: "ISBN" %>
        </div>
      </div>
    </div>

    <div class="col-10">
      <div class="form-group row">
        <label for="book_total_pages" class="col-sm-3 col-form-label">Total Pages</label>
        <div class="col-sm-9">
          <%= form.text_field :total_pages, class: "form-control required", placeholder: "Total Pages" %>
        </div>
      </div>
    </div>
    <div class="col-10">
      <div class="form-group row">
        <label for="book_published_date" class="col-sm-3 col-form-label">Published Date</label>
        <div class="col-sm-9">
          <%= form.date_field :published_date, class: "form-control required", placeholder: "Published Date" %>
        </div>
      </div>
    </div>

  <%= form.fields_for :author_attributes do |a|%>
      <div class="col-10">
        <div class="form-group row">
          <label for="book_name" class="col-sm-3 col-form-label">Author Name</label>
          <div class="col-sm-9">
            <%= a.text_field :name, class: "form-control required", placeholder: "Author Name" %>
          </div>
        </div>
      </div>
      <div class="col-10">
        <div class="form-group row">
          <label for="book_contact_number" class="col-sm-3 col-form-label">Author Contact Number</label>
          <div class="col-sm-9">
            <%= a.text_field :contact_number, class: "form-control required", placeholder: "Author Contact Number" %>
          </div>
        </div>
      </div>
  <% end %>

    <div class="col-5" data-controller="books">
      <div class="form-group">
        <%= form.submit class: "btn btn-primary", data: {action: "click->books#validate_form"} %>
      </div>
    </div>
  </div>
<% end %>
</div>
<%= link_to "Back", list_all_books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row ml-2 mr-2">
  <div class="col-12">
    <div class="mb-3">
      <%= turbo_frame_tag "new_book", src: new_book_path, target: :_top %>
      <!-- %#= link_to 'Create New Book', new_book_path, class: "btn btn-sm btn-primary mb-2" % -->
    </div>
  </div>
</div>

<div class="row ml-2 mr-2">
  <div class="col-12">
    <div class="search-block" data-controller="search">
      <form>
        <div class="row">
          <div class="col-8">
            <div class="form-group row">
              <label for="query" class="col-sm-3 col-form-label">Search Book</label>
              <div class="col-sm-9">
                <input id="query" class="form-control ml-2" type="text" name="query" data-search-target="query" data-action="keyup->search#submit">
              </div>
            </div>
          </div>
        </div>
      </form>

      <div class="mbt-3" id="search-books" data-search-target="books">
        <%= turbo_stream_from "books" %>
        <%= turbo_frame_tag "books" do %>
          <%= render @books %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/list_all.html.erb
<p id="notice"><%= notice %></p>
<div class="row" data-controller="books">
  <div class="col-6">
    <h1>Books</h1>
    <%= link_to 'New Book', form_only_for_stimulus_books_path, class: "btn btn-sm btn-primary mb-2" %>
    <br>

    <!-- table id="list-books" data-action="load@window->books#draw_books_table" -->
    <table id="list-books">
      <thead>
        <tr>
          <th>Title</th>
          <th>Total pages</th>
          <th>Isbn</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td><%= book.title %></td>
            <td><%= book.total_pages %></td>
            <td><%= book.isbn %></td>
            <td><%= link_to 'Show', book %></td>
            <td><%= link_to 'Edit', edit_book_path(book) %></td>
            <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-6">
    <!-- canvas id="myChart" width="400" height="400" data-action="load@window->books#draw_books_graph"></canvas -->
    <canvas id="myChart" width="400" height="400"></canvas>
  </div>
</div>

app/views/books/new.html.erb
<div class="col-12">
  <h1>New Book</h1>
  <%= turbo_frame_tag "new_book" do %>
    <%= render 'form', book: @book %>
  <% end %>

  <%#= link_to 'Back', books_path, class: "btn btn-sm btn-secondary" %>
</div>

app/views/books/search.html.erb
<div class="row mt-4">
  <div class="col-12">
    <div class="search-block" data-controller="search">
      <form class="form-inline">
        Search Book<input id="query" class="form-control ml-2" type="text" name="query" data-search-target="query" data-action="keyup->search#submit">
      </form>

      <div id="search-books" class="mt-3" data-search-target="books">
        <%= render partial: "book_list", locals: {books: @books} %>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Home", root_path, class: "nav-item nav-link" %>
      <%= link_to "Dashboard", list_all_books_path, class: "nav-item nav-link" %>
      <%= link_to "New book", new_book_path, class: "nav-item nav-link" %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav_bar" %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>